# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uprotocol/core/utwin/v2/utwin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uprotocol.proto.uprotocol.uoptions_pb2 as uprotocol_dot_uoptions__pb2
import uprotocol.proto.uprotocol.v1.ustatus_pb2 as uprotocol_dot_v1_dot_ustatus__pb2
import uprotocol.proto.uprotocol.v1.uri_pb2 as uprotocol_dot_v1_dot_uri__pb2
import uprotocol.proto.uprotocol.v1.umessage_pb2 as uprotocol_dot_v1_dot_umessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#uprotocol/core/utwin/v2/utwin.proto\x12\x17uprotocol.core.utwin.v2\x1a\x18uprotocol/uoptions.proto\x1a\x1auprotocol/v1/ustatus.proto\x1a\x16uprotocol/v1/uri.proto\x1a\x1buprotocol/v1/umessage.proto\"\x84\x01\n\x0fMessageResponse\x12!\n\x05topic\x18\x01 \x01(\x0b\x32\x12.uprotocol.v1.UUri\x12%\n\x06status\x18\x02 \x01(\x0b\x32\x15.uprotocol.v1.UStatus\x12\'\n\x07message\x18\x03 \x01(\x0b\x32\x16.uprotocol.v1.UMessage\"A\n\x16GetLastMessagesRequest\x12\'\n\x06topics\x18\x01 \x01(\x0b\x32\x17.uprotocol.v1.UUriBatch\"V\n\x17GetLastMessagesResponse\x12;\n\tresponses\x18\x02 \x03(\x0b\x32(.uprotocol.core.utwin.v2.MessageResponse\"@\n\x15SetLastMessageRequest\x12\'\n\x07message\x18\x01 \x01(\x0b\x32\x16.uprotocol.v1.UMessage\"\x18\n\x16SetLastMessageResponse2\x98\x02\n\x05uTwin\x12z\n\x0fGetLastMessages\x12/.uprotocol.core.utwin.v2.GetLastMessagesRequest\x1a\x30.uprotocol.core.utwin.v2.GetLastMessagesResponse\"\x04\x80\x80\x19\x01\x12w\n\x0eSetLastMessage\x12..uprotocol.core.utwin.v2.SetLastMessageRequest\x1a/.uprotocol.core.utwin.v2.SetLastMessageResponse\"\x04\x80\x80\x19\x02\x1a\x1a\xea\xf9\x18\ncore.utwin\xf0\xf9\x18\x02\xf8\xf9\x18\x00\xe0\xf9\x18\x1a\x42\x33\n#org.eclipse.uprotocol.core.utwin.v2B\nUTwinProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uprotocol.core.utwin.v2.utwin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#org.eclipse.uprotocol.core.utwin.v2B\nUTwinProtoP\001'
  _UTWIN._options = None
  _UTWIN._serialized_options = b'\352\371\030\ncore.utwin\360\371\030\002\370\371\030\000\340\371\030\032'
  _UTWIN.methods_by_name['GetLastMessages']._options = None
  _UTWIN.methods_by_name['GetLastMessages']._serialized_options = b'\200\200\031\001'
  _UTWIN.methods_by_name['SetLastMessage']._options = None
  _UTWIN.methods_by_name['SetLastMessage']._serialized_options = b'\200\200\031\002'
  _MESSAGERESPONSE._serialized_start=172
  _MESSAGERESPONSE._serialized_end=304
  _GETLASTMESSAGESREQUEST._serialized_start=306
  _GETLASTMESSAGESREQUEST._serialized_end=371
  _GETLASTMESSAGESRESPONSE._serialized_start=373
  _GETLASTMESSAGESRESPONSE._serialized_end=459
  _SETLASTMESSAGEREQUEST._serialized_start=461
  _SETLASTMESSAGEREQUEST._serialized_end=525
  _SETLASTMESSAGERESPONSE._serialized_start=527
  _SETLASTMESSAGERESPONSE._serialized_end=551
  _UTWIN._serialized_start=554
  _UTWIN._serialized_end=834
# @@protoc_insertion_point(module_scope)
