# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upayload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eupayload.proto\x12\x0cuprotocol.v1\"\x86\x01\n\x08UPayload\x12\x13\n\treference\x18\x01 \x01(\x06H\x00\x12\x0f\n\x05value\x18\x02 \x01(\x0cH\x00\x12\x13\n\x06length\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12,\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x1c.uprotocol.v1.UPayloadFormatB\x06\n\x04\x64\x61taB\t\n\x07_length*\xd8\x01\n\x0eUPayloadFormat\x12\x1f\n\x1bUPAYLOAD_FORMAT_UNSPECIFIED\x10\x00\x12\x1c\n\x18UPAYLOAD_FORMAT_PROTOBUF\x10\x01\x12\x18\n\x14UPAYLOAD_FORMAT_JSON\x10\x02\x12\x1a\n\x16UPAYLOAD_FORMAT_SOMEIP\x10\x03\x12\x1e\n\x1aUPAYLOAD_FORMAT_SOMEIP_TLV\x10\x04\x12\x17\n\x13UPAYLOAD_FORMAT_RAW\x10\x05\x12\x18\n\x14UPAYLOAD_FORMAT_TEXT\x10\x06\x42+\n\x18org.eclipse.uprotocol.v1B\rUPayloadProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upayload_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.eclipse.uprotocol.v1B\rUPayloadProtoP\001'
  _globals['_UPAYLOADFORMAT']._serialized_start=170
  _globals['_UPAYLOADFORMAT']._serialized_end=386
  _globals['_UPAYLOAD']._serialized_start=33
  _globals['_UPAYLOAD']._serialized_end=167
# @@protoc_insertion_point(module_scope)
