# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upayload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uprotocol.proto.uprotocol_options_pb2 as uprotocol__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eupayload.proto\x12\x0cuprotocol.v1\x1a\x17uprotocol_options.proto\"\x86\x01\n\x08UPayload\x12\x13\n\treference\x18\x01 \x01(\x06H\x00\x12\x0f\n\x05value\x18\x02 \x01(\x0cH\x00\x12\x13\n\x06length\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12,\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x1c.uprotocol.v1.UPayloadFormatB\x06\n\x04\x64\x61taB\t\n\x07_length*\xb7\x03\n\x0eUPayloadFormat\x12\x1f\n\x1bUPAYLOAD_FORMAT_UNSPECIFIED\x10\x00\x12G\n\'UPAYLOAD_FORMAT_PROTOBUF_WRAPPED_IN_ANY\x10\x01\x1a\x1a\xa2\xd4\x18\x16\x61pplication/x-protobuf\x12\x36\n\x18UPAYLOAD_FORMAT_PROTOBUF\x10\x02\x1a\x18\xa2\xd4\x18\x14\x61pplication/protobuf\x12.\n\x14UPAYLOAD_FORMAT_JSON\x10\x03\x1a\x14\xa2\xd4\x18\x10\x61pplication/json\x12\x34\n\x16UPAYLOAD_FORMAT_SOMEIP\x10\x04\x1a\x18\xa2\xd4\x18\x14\x61pplication/x-someip\x12<\n\x1aUPAYLOAD_FORMAT_SOMEIP_TLV\x10\x05\x1a\x1c\xa2\xd4\x18\x18\x61pplication/x-someip_tlv\x12\x35\n\x13UPAYLOAD_FORMAT_RAW\x10\x06\x1a\x1c\xa2\xd4\x18\x18\x61pplication/octet-stream\x12(\n\x14UPAYLOAD_FORMAT_TEXT\x10\x07\x1a\x0e\xa2\xd4\x18\ntext/plainB+\n\x18org.eclipse.uprotocol.v1B\rUPayloadProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upayload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.eclipse.uprotocol.v1B\rUPayloadProtoP\001'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_PROTOBUF_WRAPPED_IN_ANY"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_PROTOBUF_WRAPPED_IN_ANY"]._serialized_options = b'\242\324\030\026application/x-protobuf'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_PROTOBUF"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_PROTOBUF"]._serialized_options = b'\242\324\030\024application/protobuf'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_JSON"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_JSON"]._serialized_options = b'\242\324\030\020application/json'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_SOMEIP"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_SOMEIP"]._serialized_options = b'\242\324\030\024application/x-someip'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_SOMEIP_TLV"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_SOMEIP_TLV"]._serialized_options = b'\242\324\030\030application/x-someip_tlv'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_RAW"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_RAW"]._serialized_options = b'\242\324\030\030application/octet-stream'
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_TEXT"]._options = None
  _UPAYLOADFORMAT.values_by_name["UPAYLOAD_FORMAT_TEXT"]._serialized_options = b'\242\324\030\ntext/plain'
  _UPAYLOADFORMAT._serialized_start=195
  _UPAYLOADFORMAT._serialized_end=634
  _UPAYLOAD._serialized_start=58
  _UPAYLOAD._serialized_end=192
# @@protoc_insertion_point(module_scope)
