# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uprotocol/v1/file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17uprotocol/v1/file.proto\x12\x0cuprotocol.v1\"Z\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\x04size\x18\x02 \x01(\x04H\x00\x88\x01\x01\x12(\n\x08\x63hecksum\x18\x03 \x01(\x0b\x32\x16.uprotocol.v1.ChecksumB\x07\n\x05_size\".\n\tFileBatch\x12!\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x12.uprotocol.v1.File\"C\n\x08\x43hecksum\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.uprotocol.v1.ChecksumType\x12\r\n\x05value\x18\x02 \x01(\x0c*\\\n\x0c\x43hecksumType\x12\x1d\n\x19\x43HECKSUM_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43HECKSUM_TYPE_MD5\x10\x01\x12\x16\n\x12\x43HECKSUM_TYPE_SHA1\x10\x02\x42\x1c\n\x18org.eclipse.uprotocol.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uprotocol.v1.file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.eclipse.uprotocol.v1P\001'
  _CHECKSUMTYPE._serialized_start=250
  _CHECKSUMTYPE._serialized_end=342
  _FILE._serialized_start=41
  _FILE._serialized_end=131
  _FILEBATCH._serialized_start=133
  _FILEBATCH._serialized_end=179
  _CHECKSUM._serialized_start=181
  _CHECKSUM._serialized_end=248
# @@protoc_insertion_point(module_scope)
