# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uprotocol/v1/umessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uprotocol.proto.uprotocol.v1.uattributes_pb2 as uprotocol_dot_v1_dot_uattributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1buprotocol/v1/umessage.proto\x12\x0cuprotocol.v1\x1a\x1euprotocol/v1/uattributes.proto\"[\n\x08UMessage\x12-\n\nattributes\x18\x01 \x01(\x0b\x32\x19.uprotocol.v1.UAttributes\x12\x14\n\x07payload\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_payloadB+\n\x18org.eclipse.uprotocol.v1B\rUMessageProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uprotocol.v1.umessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.eclipse.uprotocol.v1B\rUMessageProtoP\001'
  _UMESSAGE._serialized_start=77
  _UMESSAGE._serialized_end=168
# @@protoc_insertion_point(module_scope)
