# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uprotocol/v1/uri.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16uprotocol/v1/uri.proto\x12\x0cuprotocol.v1\"\\\n\x04UUri\x12\x16\n\x0e\x61uthority_name\x18\x01 \x01(\t\x12\r\n\x05ue_id\x18\x02 \x01(\r\x12\x18\n\x10ue_version_major\x18\x03 \x01(\r\x12\x13\n\x0bresource_id\x18\x04 \x01(\r\"-\n\tUUriBatch\x12 \n\x04uris\x18\x01 \x03(\x0b\x32\x12.uprotocol.v1.UUriB\'\n\x18org.eclipse.uprotocol.v1B\tUUriProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uprotocol.v1.uri_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.eclipse.uprotocol.v1B\tUUriProtoP\001'
  _UURI._serialized_start=40
  _UURI._serialized_end=132
  _UURIBATCH._serialized_start=134
  _UURIBATCH._serialized_end=179
# @@protoc_insertion_point(module_scope)
